version: 2
jobs:        
  build:
    docker:
      - image: hashicorp/packer:1.1.1
    steps:
      - checkout # check out source code to working directory
      - run:
          name: Validate ami
          command: 
            packer validate  
                    -var 'aws_access_key=AKIAXKMRGHOQPCRDZEEH' 
                    -var 'aws_secret_key=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' 
                    -var 'aws_region=us-east-1' 
                    -var 'subnet_id=subnet-2ade3b4c' 
                    -var 'ami_users=328412259861'
                    -var 'source_ami=ami-07ebfd5b3428b6f4d' 
                    ubuntu-ami.json
      - run:
          name: build ami
          command: 
            packer build  
                    -var 'aws_access_key=AKIAXKMRGHOQPCRDZEEH' 
                    -var 'aws_secret_key=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' 
                    -var 'aws_region=us-east-1' 
                    -var 'subnet_id=subnet-2ade3b4c' 
                    -var 'ami_users=328412259861'
                    -var 'source_ami=ami-07ebfd5b3428b6f4d' 
                    ubuntu-ami.json

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
